#cloud-config
timezone: America/Toronto
locale: en_CA.UTF-8

ntp:
  enabled: true

users:
  - default

apt:
  # keep existing sources (cloud-init wipes them by default)
  preserve_sources_list: true

# add each entry to ~/.ssh/authorized_keys for the configured user or the
# first user defined in the user definition directive.
ssh_pwauth: no
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBR8dtNrWnTjdnorG28jfhd3xd4RuN5TzWGoTX+cS/oN pndurette@gmail.com

# package_upgrade: true
packages:
  - htop
  - vim

write_files:
  - path: /home/pi/~/.octoprint/config.yaml
    owner: root:root
    permissions: '044'
    content: |
      # From https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/filesystem/home/pi/.octoprint/config.yaml
      # webcam:
      #   stream: /webcam/?action=stream
      #   snapshot: http://127.0.0.1:8080/?action=snapshot
      #   ffmpeg: /usr/bin/ffmpeg
      # plugins:
      #   cura:
      #     cura_engine: /usr/local/bin/cura_engine
      #   discovery:
      #     publicPort: 80
      server:
        commands:
          systemShutdownCommand: sudo shutdown -h now
          systemRestartCommand: sudo shutdown -r now
          serverRestartCommand: sudo service octoprint restart

  # - path: /home/pi/~/.octoprint/users.yaml
  #   owner: root:root
  #   permissions: '0700'
  #   content: |
  #     #!/bin/bash

runcmd:
  - systemctl restart octoprint